---
abstract: Runtime cgiapp info in a popup window
author:
- Rhesa Rozendaal <rhesa@cpan.org>
generated_by: Dist::Zilla::Plugin::MetaYaml version 1.091260
license: perl
name: CGI-Application-Plugin-DevPopup
requires:
  CGI::Application: '4.01'
  HTML::Template: '0'
  IO::Scalar: '0'
  Test::More: '0'
  Time::HiRes: '0'
resources:
  repository: http://github.com/rhesa/cgi-application-plugin-devpopup
version: '1.05'
