--- #YAML:1.0
name:                CGI-Application-Plugin-DevPopup
version:             0.951
abstract:            Runtime cgiapp info in a popup window
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    CGI::Application:              4.01
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Rhesa Rozendaal <rhesa@cpan.org>
